### ISSUE TITLE
order changed only for 2nd level -- add force sort option for overwriting the node bundling

### ISSUE THREAD

**Issue by rolandhosner** [asjadnaqvi/stata-sankey#11]
Great new feature, thank you!

But for some reason the order of the categories is changed always and only for the 2nd "level". I have time series data, and no matter which subset of the time series I choose, or how I sort the data, it is always the 2nd "level" that changes the order of categories. 

![sankey_git](https://user-images.githubusercontent.com/97539483/231809155-093ae647-fa3d-40f1-81ce-670ad780e8f7.png)

**Comment by asjadnaqvi** [comment]
That is very strange that it would do this! Does it still persist if the graph is centered? Also the gaps between the categories are not evenly distributed.

Is it possible to share the data (partial or anonymized) for bug fixing?

**Comment by rolandhosner** [comment]
It's the same for recenter(mid) and recenter(bot).

I now tried changing the string values for the three categories - let's call them "blue", "orange", "green" - to "3_blue", "2_orange", "1_green", and that changes the order yet again for the first two months, but not for the remaining months. So it appears to have to do with the actual category names/values (for string variables).

**Comment by asjadnaqvi** [comment]
Can you check again with the new version please. If the problem still persists, then please send the and I will check
