### ISSUE TITLE
Allow custom sort by layer

### ISSUE THREAD

**Issue by zebart00** [asjadnaqvi/stata-sankey#15]
I know that sorting is constrained by space.
BUT, there are seemingly arbitrary changes in order by layer, even if I use sortby().
It would be nice if we hade the option to sort by layer. For example
sortby( 1 [dest1a] [dest1b] 2 [dest1a] [dest1b] ... )

**Comment by asjadnaqvi** [comment]
merge with #16 and #11

**Comment by asjadnaqvi** [comment]
fixed in v1.6
