### ISSUE TITLE
Allocating specific colours to each source

### ISSUE THREAD

**Issue by emfrichards** [asjadnaqvi/stata-sankey#17]
Hi Dr Naqvi,

Thanks for the great package. 

I'm hoping to assign specific colours to each path in my Sankey and then provide a key (e.g. the "worst" path is red, and the "best" path green). Is this possible?
I've seen the code for creating a new variable and colouring the Sankey by that variable, but my understanding is that only allows for one palette to be applied. 

Apologies if the answer to this question is already elsewhere/ widely known - I'm new to Stata and github!

BW,
Eleanor

**Comment by asjadnaqvi** [comment]
Dear Eleanor,

You can definitely assign different paths different colors. In your raw file, as an example, define a variable `path` which takes a value of 1 for all the good paths, and a value of 2 for bad paths.

You can call this variable in the command as follow:

```
sankey value, from(source) to(destination) by(layer) colorvar(path) palette(green red)
```

This will give 1s a green color and 2s a red color.

HTH!

Asjad
