### ISSUE TITLE
Use images for source and destination

### ISSUE THREAD

**Issue by FelixStips** [asjadnaqvi/stata-sankey#19]
This more of a feature request than a bug. Do you think it would be possible to implement the option of putting pictures instead of strings at the source and origin? The use case I am thinking about is flags for flows between countries. That would look really nice :)

**Comment by asjadnaqvi** [comment]
Adding pictures in figures is not allowed in Stata. A bunch of us have requested this feature several times but if it is implemented, definitely would add it to sankey :)
