### ISSUE TITLE
Rescaling at every layer

### ISSUE THREAD

**Issue by moritzpoll** [asjadnaqvi/stata-sankey#21]
Hi @asjadnaqvi, this is a really awesome command. I have a very particular use case for it that required me tinkering with it a little bit. I'll explain what I needed and how I got there and if you think that any of it is useful to others, I'm happy to clone and turn this into a pull request or you code it up yourself which I'm sure you'll do more cleanly than I could.

**Use case: Sampling funnel**
I want to show how in my study I went from a population to my final sample and at which step I lost how many people because of what. The key issue are the proportions. I am starting with a population of 30,000 people and am narrowing that down to a sample of 1,800. As you can see below, the later stages are barely visually discernible anymore, but arguably that's the part that matters the most.

<img width="1420" alt="image" src="https://github.com/asjadnaqvi/stata-sankey/assets/54131485/8f227d73-1423-4ee9-ac98-29cf58b3a151">

**The initial fix**
The easy fix of course is to rescale everything into percentages. I added a `percent` option to the ado and when activated, it would rescale to 100% at every layer by running these two lines right after you rename to `val1`:
```
bysort layer (var1 var2): egen total = sum(val1)
replace val1 = val1/total*100
```

<img width="1420" alt="image" src="https://github.com/asjadnaqvi/stata-sankey/assets/54131485/08baeba7-f5b1-4006-800b-01583fe10dde">

**Issue**
That admittedly mostly does the trick. But I found that visually off-putting for two reasons. First, the stock box of the group I was tracking was now disproportionately larger than the groups I was not tracking. Second, and relatedly, my eyes kind of want the curves to fan out to match the size of the box they are ending in. 

**(My) final form**
So right after `gen val2 =  val1`, this did the trick:
```
bysort var1 layer clrlvl: egen aux1 = sum(val2)
replace aux1 = 0 if clrlvl == 0
bysort layer: egen aux2 = sum(aux1)
replace val2 = val2/aux2*100
```

<img width="1420" alt="image" src="https://github.com/asjadnaqvi/stata-sankey/assets/54131485/d647fc27-0dc6-40e5-9ebd-0e41cf276064">

**Miscellaneous**
There are a few other things I changed, but they are mostly personal preference:
- Added a % symbol to the flows
- Set graph and plot region color to white (I don't use schemes)
- The column title color was bouncing around, so I fixed it to be black.
- Reversed the yscale from top to bottom as I find "ordering" categories much more intuitive that way, but that's just me.

**Comment by asjadnaqvi** [comment]
Dear Moritz, thank you for the detailed suggestion! The percent option has been requested by several people. I will add this to the next update.

**Comment by asjadnaqvi** [comment]
The "percent" code works if the subsequent categories are same or declining (balanced sankeys), as in the above graph. But if outflows are greater than the inflows (unbalanced sankeys), then it becomes a mess. This is one of the reasons why I hestiate to add it. I will still incorporate it but will also add suggestions for cautious use.

**Comment by moritzpoll** [comment]
Awesome, worked out of the box for me (unsurprisingly). Thanks so much!
