### ISSUE TITLE
class ColrSpace undefined error

### ISSUE THREAD

**Issue by joannapiechucka** [asjadnaqvi/stata-sankey#29]
Despite running a full update of the packages, I receive the following message when trying to run the _sankey_ command:
class ColrSpace undefined
(180 lines skipped)
(error occurred while loading colorpalette.ado)

**Comment by joannapiechucka** [comment]
I use Stata 18

**Comment by asjadnaqvi** [comment]
I am currently using it and it is running fine. Can you install the following and check again please:

```
ssc install palettes, replace
ssc install colrspace, replace
```

**Comment by joannapiechucka** [comment]
I have tried this, but I receive the same error still.

**Comment by asjadnaqvi** [comment]
Wierd! Send me some data and code and I will check to see if there is some code issue. Very rarely duplicate installations can cause issues with finding the correct programs. 

You can see where they are installed:

```
findfile "colorpalette.ado", all
findfile "lcolrspace.mlib", all
```

Only one version should exist in the X:/USER/ado/plus/XXX directories.

**Comment by joannapiechucka** [comment]
I changed the location of packages and now it seems to work. Sorry for bothering you with this and thank you for reaching out so quickly! very nice package!
