### ISSUE TITLE
How to make it not alphabetically order?

### ISSUE THREAD

**Issue by Kelvin17RH** [asjadnaqvi/stata-sankey#5]
<img width="590" alt="Screen Shot 2023-02-08 at 14 04 12" src="https://user-images.githubusercontent.com/113520956/217503460-a4aaa820-0f39-40bc-ac41-1f6b1c6588eb.png">

**Comment by asjadnaqvi** [comment]
Next version will have a sortby() variable.

**Comment by Kelvin17RH** [comment]
where do I've to put that sortby command? Thank you

**Comment by asjadnaqvi** [comment]
It doesn't exist yet. It will be added in the next version.

**Comment by asjadnaqvi** [comment]
added in v1.3

**Comment by Kelvin17RH** [comment]
Thank you, it helps me a lot
