### ISSUE TITLE
Suppress repeated labels -- add option to show values either on the left or the right side.

### ISSUE THREAD

**Issue by ralfminor** [asjadnaqvi/stata-sankey#7]
Dear Asjad Naqvi and others, , 

it would be great if there was an option to suppress one of the two labels per branch. In the current version, the labels always appear at the beginning and end of the branch and when there is a lot of information, this tends to make the graph confusing.

Many greetings
Ralf Minor

**Comment by asjadnaqvi** [comment]
Dear Ralf,

You can use the `labcond()` option to limit the labels you want to show. Additionally you can supress them completely and just adjust the bar labels.

![sankeytest](https://user-images.githubusercontent.com/38498046/223670409-54963417-53b3-473b-a788-5dc55c758c06.png)


If you have a concrete example and description for suggestions, then it will be helpful to provide a more specific response.

**Comment by asjadnaqvi** [comment]
fixed in v1.6
